name: create-release
on:
  push:
    branches:
    - release

jobs:
  create-tags:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install project dependencies
        run: pip install .

      - id: release
        uses: cdubos-fr/tag-python-project@main
        with:
          python-version: 3.9
          python-module: topwing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
